import { Router, type IRouter } from "express";
import healthRouter from "./health";
import bootstrapRouter from "./bootstrap";
import storageRouter from "./storage";
import meRouter from "./me";
import adminUsersRouter from "./adminUsers";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import publicRouter from "./publicCatalog";
import rawMaterialsRouter from "./rawMaterials";
import recipesRouter from "./recipes";
import inventoryRouter from "./inventory";
import productionRouter from "./production";
import transfersRouter from "./transfers";
import wholesaleOrdersRouter from "./wholesaleOrders";
import salesOrdersRouter from "./salesOrders";
import posRouter from "./pos";
import cartRouter from "./cart";
import checkoutRouter from "./checkout";
import customerRouter from "./customer";
import financialRouter from "./financial";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import employeesRouter from "./employees";
import contentBlocksRouter from "./contentBlocks";
import mediaRouter from "./media";
import settingsRouter from "./settings";
import paymentsRouter from "./payments";
import businessUnitsRouter from "./businessUnits";

const router: IRouter = Router();

router.use(healthRouter);
router.use(bootstrapRouter);
router.use(storageRouter);
router.use(meRouter);
router.use(adminUsersRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(publicRouter);
router.use(rawMaterialsRouter);
router.use(recipesRouter);
router.use(inventoryRouter);
router.use(productionRouter);
router.use(transfersRouter);
router.use(wholesaleOrdersRouter);
router.use(salesOrdersRouter);
router.use(posRouter);
router.use(cartRouter);
router.use(checkoutRouter);
router.use(customerRouter);
router.use(financialRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(employeesRouter);
router.use(contentBlocksRouter);
router.use(mediaRouter);
router.use(settingsRouter);
router.use(paymentsRouter);
router.use(businessUnitsRouter);

export default router;
